# Generated by Django 4.0.5 on 2022-06-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0002_alter_customuser_is_interviewer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Is_interviewer',
            new_name='is_interviewer',
        ),
    ]
