# Generated by Django 4.0.5 on 2022-06-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0004_rename_is_interviewer_customuser_is_interviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Is_first_time',
            field=models.BooleanField(default=True),
        ),
    ]
