# Generated by Django 4.0.5 on 2022-06-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0005_customuser_is_first_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='interviewer_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewer_technology', models.CharField(max_length=30)),
                ('interviewer_job_role', models.CharField(max_length=30)),
                ('interviewer_experience', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_technology', models.CharField(max_length=30)),
                ('user_12th_marks', models.IntegerField()),
                ('user_10th_marks', models.IntegerField()),
                ('user_CPI', models.FloatField()),
                ('user_CV', models.FileField(upload_to='')),
                ('accepted_status', models.BooleanField(default=False)),
            ],
        ),
    ]
