# Generated by Django 4.0.5 on 2022-06-10 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0006_interviewer_details_user_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewer_details',
            name='interviewer_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewer_details',
            name='interviewer_phone',
            field=models.CharField(default=1234567890, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='user_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='user_phone',
            field=models.CharField(default=1234567890, max_length=12),
            preserve_default=False,
        ),
    ]
