# Generated by Django 4.0.5 on 2022-06-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0008_rename_interviewer_id_interviewer_details_interviewer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='user_CV',
            field=models.FileField(upload_to='CV/'),
        ),
    ]
