# Generated by Django 4.0.5 on 2022-06-14 05:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0009_alter_user_details_user_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('job_role', models.CharField(default='Software Engineer', max_length=100)),
                ('job_location', models.CharField(default='remote', max_length=100)),
                ('job_description', models.CharField(default='None', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='user_details',
            name='user_CV',
            field=models.FileField(upload_to='CV/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])]),
        ),
    ]
