# Generated by Django 4.0.5 on 2022-06-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0012_remove_job_applied_company_job_applied_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_applied',
            name='company',
            field=models.ManyToManyField(to='user_login.company_details'),
        ),
        migrations.AlterField(
            model_name='job_applied',
            name='user',
            field=models.ManyToManyField(to='user_login.user_details'),
        ),
    ]
