# Generated by Django 4.0.5 on 2022-06-14 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0013_alter_job_applied_company_alter_job_applied_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_applied',
            name='company',
        ),
        migrations.AddField(
            model_name='job_applied',
            name='company',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_login.company_details'),
        ),
        migrations.RemoveField(
            model_name='job_applied',
            name='user',
        ),
        migrations.AddField(
            model_name='job_applied',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_login.user_details'),
        ),
    ]
