# Generated by Django 4.0.5 on 2022-06-14 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0014_remove_job_applied_company_job_applied_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_applied',
            name='application_status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='job_applied',
            name='company',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_login.company_details'),
        ),
        migrations.AlterField(
            model_name='job_applied',
            name='user',
            field=models.ForeignKey(default=5, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_login.user_details'),
        ),
    ]
