# Generated by Django 4.0.5 on 2022-06-14 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0015_alter_job_applied_application_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_applied',
            name='application_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=40),
        ),
        migrations.AlterField(
            model_name='job_applied',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_login.company_details'),
        ),
        migrations.AlterField(
            model_name='job_applied',
            name='user',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='user_login.user_details'),
        ),
    ]
